//#defines and enums and shit to go here
#ifndef _DEFINITIONS_H_
#define _DEFINITIONS_H_

// IMPORTANT
#include <Windows.h>
#include <d3dx9math.h>
#include <iostream>

// STL //
#include <vector>
#include <string>
#include <list>
/**************/
class IBaseObject;
typedef void(*Behavior)(IBaseObject*,float);

// OBJECT FACTORY //
#define MAX_PLAYERS			4
#define MAX_BULLETS_PLAYER	250
#define MAX_BULLETS_ENEMY	250
#define MAX_BULLETS_EXP		50
#define MAX_BULLETS_TESLA	250
#define MAX_BULLETS_BEAM	50
#define MAX_BULLETS_ARC		50
#define MAX_PICKUP			50
#define MAX_TRASH			100
#define MAX_PATROL			50
#define MAX_SMASH			50
#define MAX_BURN			50
#define MAX_SPIDER			10
#define	MAX_STEAM			1
#define MAX_AICORE			1
#define MAX_AIFIST			2
#define MAX_CONVEYOR		70
#define MAX_VAT				50
#define MAX_CRATE			50
#define MAX_BARREL			50
#define MAX_POOL			100
#define MAX_TUNNEL			20
#define MAX_TURRETS			10
#define MAX_INVERSION		20
#define MAX_BOSSINV			1
#define MAX_PITS			25
#define MAX_BOSSTURRET		4
#define MAX_SPINBOT			1
#define MAX_FLOOR			1

#define MAXHP_PLAYER		100.0f
#define MAXHP_TRASH			50.0f
#define MAXHP_SMASH			500.0f
#define MAXHP_PATROL		25.0f
#define MAXHP_BURN			200.0f
#define MAXHP_SPIDER		1100.0f
#define MAXHP_STEAM			7000.0f
#define MAXHP_AICORE		4000.0f
#define MAXHP_AIFIST		7000.0f
#define MAXHP_VAT			150.0f
#define MAXHP_SPINBOT		7000.0f

enum eEffects { EFFECT_SMALLEXP, EFFECT_MEDEXP, EFFECT_INVULSPARK, EFFECT_TESLASPRAY, EFFECT_PULSEHIT, EFFECT_BULLETHIT, EFFECT_TESLAHIT, EFFECT_PLAYERDMG, EFFECT_MOLTENBURN,
				EFFECT_DMGEXPLOSION, EFFECT_SMOKE, EFFECT_SMOKEBURN, EFFECT_BURN, EFFECT_LASER, EFFECT_PLAYERDEATH, EFFECT_SPECIALHIT, EFFECT_SMASHWAVE, EFFECT_SPECIAL,
				EFFECT_SPIDERFIRE, EFFECT_DASH };

enum eObjects { OBJ_PLAYER, OBJ_SPINBOT, OBJ_TRASH = 5, OBJ_PATROL, OBJ_SMASH, OBJ_BURN, OBJ_STEAM, OBJ_AICORE, OBJ_SPIDER,
	OBJ_AIFIST, OBJ_INVERSION, OBJ_CONVEYOR, OBJ_VAT, OBJ_CRATE, OBJ_TURRET, OBJ_BARREL, OBJ_POOL, OBJ_TUNNEL, OBJ_DEFENSELASER, OBJ_BOSSINV, OBJ_BOSSTURRET, OBJ_GATLING, OBJ_BEAM, OBJ_TESLA,
	OBJ_BULLET_EXP, OBJ_BULLET_TESLA, OBJ_BULLET_BEAM, OBJ_BULLET_ENEMY, OBJ_BULLET_PLAYER, OBJ_BULLET_ARC, OBJ_PLAYERTREAD, OBJ_PLAYERHEAD_BLUE, OBJ_PLAYERHEAD_GREEN,
	OBJ_AI_HEAD, OBJ_AI_MONITORS, OBJ_AI_ARMS, OBJ_PIT, OBJ_STEAM_WHEEL, OBJ_PLAYERBOTTOM, OBJ_SMASHBOTTOM, OBJ_PICKUP, OBJ_FLOOR, OBJ_GATE, OBJ_MIDBOSSFLOOR, OBJ_NUM_OBJECTS};
enum eEffectObjects { EFFECT_OBJ_PLANE = OBJ_NUM_OBJECTS, EFFECT_OBJ_CIRCLE, EFFECT_OBJ_CUBE, EFFECT_OBJ_CYLINDER, EFFECT_OBJ_DISC, EFFECT_OBJ_SPHERE, EFFECT_OBJ_TORUS, EFFECT_OBJ_WAVE, EFFECT_OBJ_SHOCKWAVE, EFFECT_OBJ_ANIMATION, OBJ_TOTAL_OBJECTS };
enum eEvents { EVENT_AICORE=100, EVENT_ASSBOSS, EVENT_FOUNDBOSS, EVENT_NUM_EVENTS };

enum eObjectGroups { OM_PLAYERS, OM_PLAYER_BULLETS, OM_PLAYER_SP, OM_ENEMIES, OM_ENEMY_BULLETS, OM_ENVIRONMENT, OM_NUM_OBJECTS };

enum eBulletType {ENEMYBULLET, SMASHBULLET, SPECIALBULLET,BARRELBULLET, STANDARD, GATLING, BEAM, TESLA, ARC, INVERSION_BULLET};
enum eRenderGroups { RG_ENVIRONMENT, RG_MODELS, RG_BULLETS, RG_TRANSPARENT, RG_NUM_GROUPS };
enum ePickUpType { PU_GATLING, PU_BEAM, PU_TESLA, PU_NUM_PICKUPS };


enum eInputForms {UP = 1, DOWN = (1<<1), LEFT = (1<<2), RIGHT = (1<<3), UP_LEFT = (1<<4), UP_RIGHT = (1<<5), DOWN_LEFT = (1<<6), DOWN_RIGHT = (1<<7), SHOOT_UP= (1<<13), SHOOT_DOWN = (1<<14), SHOOT_LEFT = (1<<15),
					SHOOT_RIGHT = (1<<16), SHOOT_UP_LEFT = (1<<17), SHOOT_UP_RIGHT = (1<<18), SHOOT_DOWN_LEFT = (1<<19), SHOOT_DOWN_RIGHT = (1<<20), SPECIAL = (1<<8), DASH = (1<<9), PAUSE = (1<<10), ACCEPT = (1<<11), BACK = (1<<12)};

enum eDifficulty {NORMAL = 1, HARD,NUM_DIFF};
enum eBeingHit {NOTHIT = 0, ENEMYHIT, PLAYERHIT, BURNEXPLODE};

enum eAvoidFlags { AVOID_LEFT = 1, AVOID_RIGHT = (1<<1), AVOID_CENTER = (1<<2) };

/******************************************************************/

#define PLAYER_SPEED		8.0f
#define PLAYER_DASH_SPEED	18.0f
#define PLAYER_DASH_TIME	.3f
#define PLAYER_DASH_COST	200.0f
#define PLAYER_DASH_REGEN	50.0f
#define PLAYER_MAX_ENERGY	50.0f
#define PLAYER_TURN			720.0f

#define BULLET_HEIGHT_OFFSET 1.105f
// WEAPON STATS
#define BULLET_SPEED			30.0f
#define BULLET_STD_SIZE			.2f
#define STANDARD_WEAPON_SPEED	.17f
#define WEAPON_DURATION			7.5f
#define WEAPON_PICKUP_DELAY		WEAPON_DURATION - 1.0f
#define GATLING_WEAPON_SPEED	.03f
#define GATLING_PUSHBACK		2.3f
#define BEAM_RADIUS				1.0f
#define BEAM_WEAPON_SPEED		0.5f
#define BEAM_WEAPON_LIFE		0.1f
#define TESLA_WEAPON_SPEED		0.0f
#define TESLA_WIDTH				6.0f
#define TESLA_HEIGHT			5.5f
#define PLAYER_SP_SPEED			30.0f
#define PLAYER_SP_MAXRADIUS		6.0f

// DAMAGES
#define DMG_STDWEAPON	25.0f
#define DMG_GATGUN		DMG_STDWEAPON*0.5f
#define DMG_BEAM		1500.0f
#define DMG_TESLA		150.0f
#define DMG_SPECIAL		500.0f

#define TRASHBOT_SPEED		4.0f
#define TRASHBOT_SPEED_SQ	TRASHBOT_SPEED * TRASHBOT_SPEED
#define TRASHBOT_ROT_SPEED	180.0f
#define SMASHBOT_SPEED		3.0f
#define SMASHBOT_ROT_SPEED	90.0f
#define SMASHBOT_CHARGETIME	0.5f
#define SMASHBOT_AOESPEED	30.0f
#define SMASHBOT_RADIUS		4.0f
#define SMASHBOT_ATKRADIUS	5.5f
#define SMASHBOT_TOTAL		SMASHBOT_CHARGETIME + 1.3f
#define PBOT_SPEED			7.0f
#define PBOT_BULLET_SPEED	10.0f
#define CORE_FIRE_SPEED		2.5f
#define SPIDER_FIRE_SPEED	1.5f
#define TURRET_HP			800.0f
#define TURRET_DMG			30.0f
#define TURRET_RADIUS		0.3f
#define SPINBOT_MOVESPEED	15.0f
#define SPINBOT_ROTSPEED	270.0f

//Inversion Tower #defines
#define MAXHP_INVERSION		700.0f
#define INVERSION_RADIUS	0.75f

#define BURN_SPEED			7.0f
#define BURN_ROT_SPEED		270.0f
#define BURN_CHARGETIME		0.5f
#define BURN_AOESPEED		30.0f
#define BURN_RADIUS			4.0f
#define BURN_DAMAGE			50.0f

#define MOLTEN_DAMAGE		20.0f
#define MOLTEN_COLOR		D3DXVECTOR4(1.0f, 0.3f, 0.1f, 0.75f)

#define BARREL_DAMAGE		25.0f
#define BARREL_RADIUS		2.0f
#define BARREL_SPEED		50.0f

#define MAX_BULLET_LIFE 3.0f
#define EPISILON 0.000001f
#define HIT_CAP 0.1f
#define PLAYER_HIT_CAP 0.5f
#define PICKUP_LIFETIME 15.0f

#define SMASHBOT_DAMAGE 35.0f
#define GRAVITY -18.0f
#define ANITIGRAVITY 35.0f
#define CEILING	18.0f
#define ARCBULLET_SPEED 20.0f
#define ARCBULLET_SHRAPSPEED 25.0f
#define AVOID_SAFE_RADIUS 6.0f


// COLORS
#define COLOR_PLAYER		D3DXVECTOR4(0.0f, 0.0f, 1.0f, 1.0f)
#define COLOR_PLAYER_HIT	D3DXVECTOR4(0.5f, 0.5f, 0.5f, 1.0f)
#define COLOR_ENEMY_BULLET		D3DXVECTOR4(1.0f, 0.3f, 0.0f, 1.0f)
#define COLOR_TRASHBOT		D3DXVECTOR4(1.0f, 0.0f, 0.0f, 1.0f)
#define COLOR_TRASHBOT_HIT	D3DXVECTOR4(1.0f, 1.0f, 0.0f, 1.0f)
#define COLOR_SMASHBOT		D3DXVECTOR4(1.0f, 0.0f, 0.0f, 1.0f)
#define COLOR_SMASHBOT_HIT	D3DXVECTOR4(1.0f, .5f, 1.0f, 1.0f)
#define COLOR_BULLET_PLAYER	D3DXVECTOR4(1.0f, 1.0f, 1.0f, 1.0f)
#define COLOR_SMASHBOT_AOE	D3DXVECTOR4(.75f, .75f, .75f, 1.0f)
#define COLOR_SMASHBOT_VUL	D3DXVECTOR4(0.0f, 0.0f, 1.0f, 1.0f)
#define COLOR_PATROLBOT     D3DXVECTOR4(0.0f, 1.0f, 0.0f, 1.0f)
#define COLOR_PATROLBOT_HIT	D3DXVECTOR4(1.0f, 1.0f, 1.0f, 1.0f)
#define COLOR_SPECIAL		D3DXVECTOR4(0.0f, 0.0f, 1.0f, 1.0f)
#define COLOR_BURN_AOE		D3DXVECTOR4(0.85f, 0.0f, 0.0f, .75f)
#define COLOR_AICORE		D3DXVECTOR4(1.0f, 0.0f, 0.0f, 1.0f)

//Camera Offset
#define CAM_ZOFF 6.0f

#endif
